version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - farfetch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    links:
      - elasticsearch
      - kafka
    volumes:
      - ./:/config-dir
    command: logstash -f /config-dir/logstash.conf
    ports:
      - 9600:9600
    networks:
      - farfetch
    depends_on:
      - elasticsearch

  zookeeper:
    image: zookeeper
    networks:
      - farfetch

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - 9092:9092
    networks:
      - farfetch

  gender_service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      ES_HOST: elasticsearch
    command: bundle exec ruby gender_service.rb
    ports:
      - "4567:4567"
    networks:
      - farfetch
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local

networks:
  farfetch:
